project:
  title: "Online Dictionary of Zilo Andi"
  output-dir: ./docs

website:
  search: false
  favicon: favicon.png
  navbar:
    right:
      - href: ./ru/index.html
        text: Русский

lang: en
