project:
  title: "Электронный словарь зиловского андийского"
  output-dir: ./docs/ru

website:
  search: false
  favicon: favicon.png
  navbar:
    right:
      - href: ../index.html
        text: English

lang: ru
